---
layout: post
title: "Working with Lidar Data"
date:   2015-10-22 20:49:52
authors: "Keely Roth, Mike Alonzo, Jonah Duckles"
dateCreated:  2015-10-22 20:49:52
lastModified: 2015-10-22 14:28:52
category: remote-sensing-workshop
tags: [module-1]
mainTag: GIS-Spatial-Data
description: "This post explains the fundamental principles, functions and metadata that you need to work with raster data in R."
code1:
image:
  feature: lidar_GrandMesa.png
  credit: LiDAR data collected over Grand Mesa, Colorado - National Ecological Observatory Network (NEON)
  creditlink: http://www.neoninc.org
permalink: /R/Raster-Data-In-R/
code1: /R/2015-07-22-Introduction-to-Raster-Data-In-R.R
comments: true

---

<section id="table-of-contents" class="toc">
  <header>
    <h3>Contents</h3>
  </header>
<div id="drawer" markdown="1">
*  Auto generated table of contents
{:toc}
</div>
</section><!-- /#table-of-contents -->


## About
* Exploring Spatial patterns in Lidar Data: histograms,
* Summarizing lidar data: binary binning/thresholding, etc.

## R Skills Level
Intermediate (link to other group's lessons)

### Background

## Learning Objectives
* (C) understand the measurement and where it comes from
  point cloud to raster concepts (gridding): Creation of products (DTM,
    CSM,
  CHM) imaging/data collect; tabular data
* (C) ecology of canopy height (what information does it give us that is
  useful?) what does gridded height imply? how it’s different (and the
    same)
  from field data what might variation in CHM show?
* (T) Plot the study area (geotiff 1 km sq file) and explore pixel values
colors transect
* (T) Overlay and extract 2 study regions
* (T) Display the 2 regions
* (T) Create and threshold histograms in the two regions
* (T) More advanced analysis: spatial pattern using standard deviation/moving window (only doing this for chm, not hyperspectral)

### R libraries
* `raster`
* `rgdal`
* `rhdf5`

``` {r}
install.packages('raster')
install.packages('rgdal')
install.packages('rhdf5')

library('raster')
library('rgdal')
library('rhdf5')
```
